# -*- coding: utf-8 -*-
"""1min_chunk.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vM9f2o2JtL6IIG3DJzJYA4s0bJEQZIZ5
"""

from pydub import AudioSegment
import os

def combine_audio_files(input_folder):
    combined_audio = AudioSegment.empty()

    # Iterate through all the files in the input folder
    for filename in os.listdir(input_folder):
        if filename.endswith(".wav"):
            input_file = os.path.join(input_folder, filename)

            # Load the input audio using pydub
            audio = AudioSegment.from_file(input_file)

            # Append the audio to the combined audio
            combined_audio += audio

    return combined_audio

def split_audio_into_chunks(audio, chunk_duration):
    # Create an output directory
    # output_directory = 'input_folder/chunks'
    if not os.path.exists(output_directory):
        os.makedirs(output_directory)

    # Calculate the total duration of the audio in milliseconds
    total_duration = len(audio)

    # Split the audio into one-minute chunks
    chunk_index = 1
    start_time = 0

    while start_time + chunk_duration * 1000 <= total_duration:
        end_time = start_time + chunk_duration * 1000

        # Generate the output filename
        output_file = os.path.join(output_directory, f"chunk_{chunk_index}.wav")

        # Extract the chunk from the audio and export as a single audio file
        chunk = audio[start_time:end_time]
        chunk.export(output_file, format="wav")

        # Update the start time and chunk index for the next chunk
        start_time = end_time
        chunk_index += 1



input_folder = input("Enter the path to the input folder: ")
output_directory = os.path.join(input_folder, 'chunks')

chunk_duration = 60  # in seconds

# Combine all the audio files in the input folder
combined_audio = combine_audio_files(input_folder)

# Split the combined audio into one-minute chunks
split_audio_into_chunks(combined_audio, chunk_duration)



